services:
  database:
    build:
      context: ./database
    container_name: dsf-database
    environment:
      POSTGRES_DB: ${DB_NAME:-desafio_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-desafio_db}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    stop_grace_period: 30s

  backend:
    build: ./backend
    container_name: dsf-backend
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-desafio_db}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    stop_grace_period: 30s

  frontend:
    build: ./frontend
    container_name: dsf-frontend
    networks:
      - internal_network
    restart: unless-stopped
    stop_grace_period: 10s

  proxy:
    build: ./proxy
    container_name: dsf-proxy
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - internal_network
      - external_network
    restart: unless-stopped
    stop_grace_period: 10s

networks:
  internal_network:
    internal: true
    ipam:
      config:
        - subnet: "10.10.0.0/24"
  
  external_network:
    ipam:
      config:
        - subnet: "10.10.1.0/24"

volumes:
  postgres_data: