apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio-devops
type: Opaque
data:
  POSTGRES_DB: ZGVzYWZpb19kYg== # desafio_db
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password